### ISSUE TITLE
GenericWaitForEventFuture doesn't handle task migration.

### ISSUE THREAD

**Issue by sfackler** [Matthias247/futures-intrusive#18]
Its poll implementation only saves off its waker on the first poll, but not subsequent ones: https://github.com/Matthias247/futures-intrusive/blob/master/src/sync/manual_reset_event.rs#L107-L113. If the future's task is migrated from one executor to another, its waker will change but won't be updated internally and so won't be awoken appropriately when the event is triggered.

It just needs this in the `PollState::Waiting` case:

```rust
if wait_node.task.as_ref().map_or(true, |w| !w.will_wake(cx.waker())) {
    wait_node.task = Some(cx.waker().clone());
}
```

**Comment by Matthias247** [comment]
You are right. The same probably also applies to other `Future`s. I now recall a discussion on discord (or somewhere else?) where the question was whether `Waker`s should actually be updated. I think some mentioned "no", but strictly speaking it's the right thing to do. I will push an update.

I am not sure whether you can really move the `Future` between tasks. It at least has to be pinned, and thereby it is already very restricted what you can do with it. Executors will likely always be passing the same `Waker`, but it's better not to rely on it.

`will_wake()` sounds good to avoid the refcount churn - but I just discovered that it's broken due to the executor optimizations:  Those sometimes pass a different `Waker` reference which only on `.clone()` gets transformed into the real `Waker`. E.g. futures-rs does it [here](https://github.com/rust-lang-nursery/futures-rs/blob/master/futures-task/src/waker_ref.rs). That saves the refcount increase and decrease on the executor - but now causes `will_wake()` to always return `false`.

**Comment by sfackler** [comment]
> I am not sure whether you can really move the Future between tasks.

It is possible, but I'm not sure you'd ever really see it in "normal" code. You could for example make a future that contains a `Pin<Box<impl Future>>`, polls it once and then sends it on a channel to a task running on another executor.

**Comment by Matthias247** [comment]
This should be fixed now. I checked all `Pending` returns and added updates for the `Waker`.
