### ISSUE TITLE
`Semaphore` cost O(waiters) time to wake up on, and quadratic in total

### ISSUE THREAD

**Issue by oxalica** [Matthias247/futures-intrusive#24]
I'm trying to limit concurrent requests using `Semaphore`. But the `Semaphore` itself cost tons of time when there are quite a lot of futures trying to acquire it.

For example, this code spawns 10^4 futures and should run in 10000 / 100 = 100ms. But it costs 3.06s in fact. For 2*10^4 futures, it costs 14.40s (expect to be 200ms) !
```rust
extern crate async_std; // features = ["attributes"]
extern crate futures_intrusive;
use async_std::task::{sleep, spawn};
use futures_intrusive::sync::Semaphore;
use std::{sync::Arc, time::Duration};

async fn send_request() {
    // Send requests...
    sleep(Duration::from_millis(1)).await;
}

#[async_std::main]
async fn main() {
    let sem = Arc::new(Semaphore::new(false, 100));
    let hs = (0..10000)
        .map(|_| {
            let sem = sem.clone();
            spawn(async move {
                let _guard = sem.acquire(1).await;
                send_request().await;
            })
        })
        .collect::<Vec<_>>();
    for h in hs {
        h.await;
    }
}
```

I use `cargo-flamegraph` to do profiling, which shows that it cost a lot on peeking the last element from single linked list. [Related code](https://github.com/Matthias247/futures-intrusive/blob/master/src/sync/semaphore.rs#L74).
![Screenshot_20191219_210607](https://user-images.githubusercontent.com/14816024/71175930-a5821200-22a3-11ea-9a12-39cf001f536b.png)

It seems to be **designed to** wake the **last** waiter. But why it is still required even when `!is_fair`?

**Comment by Matthias247** [comment]
It's pretty easy to improve:

Before:

```
matthias@Matthiass-MBP  ~/Code/rust/futures-intrusive (test *)
$cargo run --example abc --release
    Finished release [optimized] target(s) in 0.09s
     Running `target/release/examples/abc`
Elapsed: 3361ms
```

After:

```
matthias@Matthiass-MBP  ~/Code/rust/futures-intrusive (test *)
$cargo run --example abc --release
   Compiling futures-intrusive v0.2.2 (/Users/matthias/Code/rust/futures-intrusive)
    Finished release [optimized] target(s) in 2.85s
     Running `target/release/examples/abc`
Elapsed: 138ms
```

Most wait lists in the library currently use a single linked list, which requires an O(n) iteration for some operations, but only requires to store a single pointer which minimizes the size of `Future`s. With the typical amount of tasks that interact with a wait list (which might be well below 100) that is not really an issue. But with your high numbers it certainly gets excessive slow.

Changing to a double linked list (which is a single line code change - since the list is already implemented) fixes the issue - at the cost of storing an additional pointer per `Future`. For `Semaphore` I'm definitely convinced that this seems to be the better tradeoff, since people would use it like you to let a big number of tasks wait on it, so let's make the change. For other things like Channels I'm still undecided.

> It seems to be designed to wake the last waiter. But why it is still required even when !is_fair?

The idea here certainly was that the cost difference between waking the last or the first waiter isn't that high. And that waking the oldest waiter at least retains some amount of fairness.

**Comment by Matthias247** [comment]
The behavior is now changed in master for all primitives that are part of the `sync` module
