### ISSUE TITLE
Send/Receive futures aren't Sync or Send

### ISSUE THREAD

**Issue by sfackler** [Matthias247/futures-intrusive#3]
I believe this is because they contain `&dyn ChannelSendAccess` and `&dyn ChannelReceiveAccess` trait objects internally.

Minimally, being Send would enable them to be used on the multi-threaded tokio runtime.

**Comment by Matthias247** [comment]
Yup, I'm aware of that and also wanted to create an issue.

In the inital versions it actually was, but there the futures had been generic over the mutex type, which allowed for `impl <MutexType: Sync> Send for Future<MutexType>`.

Since I wanted to reduce the number of generic parameters in the APIs I moved to dynamic dispatch from the futures to their sources. Unfortunately I missed there the implications on multithreaded runtimes.

Moving back to generic futures is certainly an alternative, but I'm wondering whether there is a better one which doesn't require the propagation of mutex parameters. There could be 2 versions like `SendFuture` and `LocalSendFuture`, where only the first is `Sync`. But I'm not sure how to return those without building wrappers manually around the generic channel type - since that one would just return `GenericSendFuture<MutexType>`.

Any good idea here is appreciated!

**Comment by sfackler** [comment]
I think parameterizing the futures might be the best solution honestly. To keep the API from getting too complex, though, you could have the methods return `impl Future` rather than the concrete, generic type potentially.

**Comment by Matthias247** [comment]
I think besides the API getting complicated another concern is compile times and code size. If future type generates different code for every different array buffer size that is used it might be an unnecessary bloat. I'm not sure how good LLVM is at optimizing/deduplicating this - The type is actually used nowhere in the code, so it might get deduped?

I'm playing a little bit more around with this, since obviously being able to use the library with multithreaded executors is important.

> you could have the methods return impl Future rather than the concrete, generic type potentially.

I think I had that in the beginning, but then moved to concrete types. I don't recall the exact reasons, but it might have been along:
- Rest of the ecosystem does it too
- It is sometimes helpful to be able to name the futures

I now tried this again, and I run into issues with using the anonymous futures in traits like here: https://github.com/Matthias247/futures-intrusive/blob/master/tests/mpmc_channel.rs#L704

Maybe I'm doing something wrong (those things get really complicated, and sometimes the answer unfortunately is "we need existential types" or "we need GATs" to make this work.

**Comment by Matthias247** [comment]
@sfackler I implemented now something for channels in #4 

Would appreciate any opinion. Once channels are done something similar would need to be done for the other types in the library.

**Comment by sfackler** [comment]
Thinking about it a bit more, I don't think that adding a "normal" second type parameter would actually bloat things up all that much. The future already has to parameterize by the channel's value type, and my gut feeling is that there aren't going to be a ton of use cases where you have tons of distinct channel types with differing mutex implementations but the same values.

**Comment by Matthias247** [comment]
Agreed, programs will only make use of one Mutex type. The flexibility is provided mainly by the library to allow for no-std use-cases (e.g. in a RTOS) and for the LocalChannel optimization. So I'm also not afraid of bloat through that.

The same wouldn't be true for channels with the same type but different array length, e.g. `Channel<i32, [i32; 0]>` and `Channel<i32, [i32; 64]>` which might occur in the same program. Whether that's an issue - I don't know.

I think my main reason for keeping dynamic dispatch and opting for `Future<MutexType, T>` is that it's still a little more ergonomic than returning `Future<GenericChannel<MutexType, T,  A>, T>`.

**Comment by sfackler** [comment]
With a couple of typedefs you could have `ChannelFuture<MutexType, T, A>`, which isn't any worse than the `Channel<MutexType, T, A>` that users deal with now.

**Comment by Matthias247** [comment]
`ChannelFuture` is also used for the oneshot channel, which doesn't have the extra `A` parameter.

**Comment by Matthias247** [comment]
I just published version 0.2 which should have versions of all Futures which are compatible with multithreaded executors

**Comment by Matthias247** [comment]
I'm marking this as closed for now since the 0.2 should fulfill the requirement. For any further API discussion we can open a new issue.
