### ISSUE TITLE
Pulling out intrusive data structures into another crate

### ISSUE THREAD

**Issue by sujayakar** [Matthias247/futures-intrusive#48]
Would you all be open to moving the intrusive linked list and pairing heap into another crate? I'd like to write some specialized channel data structures, and having these primitives available would help a lot.

If so, I'm happy to do it!

**Comment by Matthias247** [comment]
Have you taken a look at the [intrusive-collections](https://docs.rs/intrusive-collections/0.9.0/intrusive_collections/) crate? It's awesome, and I also use it in some places.

However it's a bit too strict for what is required in this crate, since the lifetime relations here can not be expressed in safe Rust. Therefore I wrote a custom implementation.

Since those are however not 100% safe and the APIs decisions might be a bit controversial I'm hesitant on publishing them as a seperate crate. Feel free to copy&paste everything you need for your projects

**Comment by sujayakar** [comment]
Ah, yeah I want to take advantage of the tricks you're doing here with pinning to avoid heap allocation for waiters, and it doesn't look like `intrusive-collections` takes advantage of `Pin`, right?

> Since those are however not 100% safe and the APIs decisions might be a bit controversial I'm hesitant on publishing them as a seperate crate. Feel free to copy&paste everything you need for your projects
Sounds good!
