### ISSUE TITLE
Possible breaking change in 0.4.1 release

### ISSUE THREAD

**Issue by kczimm** [Matthias247/futures-intrusive#66]
I ran into an issue using the `switchyard` crate, see https://github.com/BVE-Reborn/switchyard/issues/20. It depends on both `futures-intrusive` and `parking_lot` but only using their minor versions, `0.4` and `0.11` respectively. This works fine with `futures-intrusive = "0.4.0"` because it uses the same minor version of `parking_lot` but running `cargo update` getting `futures-intrusive = "0.4.1"` breaks it. Is this because the `parking_lot::RawMutex` is in the public API of `futures-intrusive`? If that is the case, then I think "0.4.1" would need to be yanked and replaced with "0.5.0".

**Comment by kczimm** [comment]
Specifically, isn't `OneshotSender` exposing `parking_lot::RawMutex` in the public API of `futures-intrusive`? https://docs.rs/futures-intrusive/0.4.1/futures_intrusive/channel/shared/type.OneshotSender.html

**Comment by Matthias247** [comment]
Thanks for the notice. I feared something like this would happen, that's why I actually refrained from pushing a new version just because the dependency updated. I knew lock-api was part of the public API but missed that parking-lot is too due to generics.

Anyhow, it should be fixed now:
- 0.4.1 is yanked
- 0.4.2 uses is reverted back to parking lot 0.11
- 0.5.0 is using parking lot 0.12
